# Introduction to Pandas DataFrames

This notebook demonstrates basic pandas DataFrame operations using Python and Jupyter Notebook.

The examples include:

- Creating a DataFrame
- Viewing rows
- Displaying information
- Generating statistics
- Selecting columns

## Pandas Library

`pandas` is a Python library used for data analysis and data manipulation.

In [18]:
# Python version is 3.13.9

import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John", "Mina"],
    "Age": [25, 30, 22, 28],
    "City": ["Baghdad", "Erbil", "London", "Berlin"]
}

df = pd.DataFrame(data)

df

   Name  Age     City
0   Ali   25  Baghdad
1  Sara   30    Erbil
2  John   22   London
3  Mina   28   Berlin

## Displaying the First Rows

The head() function displays the first rows of the DataFrame.

In [29]:
df.head(2)

   Name  Age     City
0   Ali   25  Baghdad
1  Sara   30    Erbil

## DataFrame Information

The info() function provides information about the structure and data types.

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   City    4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

## Statistical Summary

The describe() function generates descriptive statistics.

In [31]:
df.describe()

         Age
count   4.00
mean   26.25
std     3.50
min    22.00
25%    24.25
50%    26.50
75%    28.50
max    30.00

In [32]:
df.describe()

         Age
count   4.00
mean   26.25
std     3.50
min    22.00
25%    24.25
50%    26.50
75%    28.50
max    30.00

## Selecting a Column

Specific columns can be selected using square brackets.

In [33]:
df["Name"]

0     Ali
1    Sara
2    John
3    Mina
Name: Name, dtype: str

# Introduction to Pandas DataFrames

## Pandas Library

pandas is a Python library used for data analysis and data manipulation.

## Creating a DataFrame

The following example creates a simple pandas DataFrame containing names, ages, and cities.

## Creating a DataFrame

The following example creates a simple pandas DataFrame containing names, ages, and cities.

![Pandas Library](Pandas.webp)

[pandas documentation](https://pandas.pydata.org/)

*pandas* is widely used for data analysis.

| Function | Description |
|---|---|
| `head()` | Displays first rows |
| `info()` | Displays structure |